// <auto-generated />
using System;
using Main.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;

#nullable disable

namespace Main.Infrastructure.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260320085622_AddMessageAttachment")]
    partial class AddMessageAttachment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Main.Domain.Aggregates.Chat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FolderId")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("folder_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<string>("ModelId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("model_id");

                    b.Property<int>("NextSequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("next_sequence_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<NpgsqlTsVector>("TitleSearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("title_search_vector")
                        .HasComputedColumnSql("to_tsvector('english', title)", true);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chats");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("ix_chats_folder_id");

                    b.HasIndex("TitleSearchVector")
                        .HasDatabaseName("ix_chats_title_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TitleSearchVector"), "GIN");

                    b.HasIndex("UserId", "FolderId", "UpdatedAt")
                        .HasDatabaseName("ix_chats_user_id_folder_id_updated_at");

                    b.HasIndex("UserId", "IsArchived", "UpdatedAt")
                        .HasDatabaseName("ix_chats_user_id_is_archived_updated_at");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Aggregates.Folder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("normalized_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_folders");

                    b.HasIndex("UserId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_folders_user_id_normalized_name");

                    b.HasIndex("UserId", "SortOrder")
                        .HasDatabaseName("ix_folders_user_id_sort_order");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Aggregates.Preference", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("MemoryEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("memory_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_preferences");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_preferences_user_id");

                    b.ToTable("preferences", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Aggregates.SharedChat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("model_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("SnapshotAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("snapshot_at");

                    b.Property<string>("SourceChatId")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("source_chat_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.HasKey("Id")
                        .HasName("pk_shared_chats");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_shared_chats_owner_id");

                    b.HasIndex("SourceChatId")
                        .HasDatabaseName("ix_shared_chats_source_chat_id");

                    b.ToTable("shared_chats", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Aggregates.Workflow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id");

                    b.Property<int>("ConsecutiveFailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failure_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("DaysOfWeekMask")
                        .HasColumnType("integer")
                        .HasColumnName("days_of_week_mask");

                    b.Property<string>("DeliveryPolicy")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("delivery_policy");

                    b.Property<Guid?>("DispatchLeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispatch_lease_id");

                    b.Property<DateTimeOffset?>("DispatchLeaseUntilUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("dispatch_lease_until_utc");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_run_at");

                    b.Property<string>("LocalTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("local_time");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("model_id");

                    b.Property<DateTimeOffset>("NextRunAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_run_at");

                    b.Property<string>("NormalizedInstruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_instruction");

                    b.Property<string>("PauseReason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("pause_reason");

                    b.Property<string>("RecurrenceKind")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("recurrence_kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UseWebSearch")
                        .HasColumnType("boolean")
                        .HasColumnName("use_web_search");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_workflows_user_id_status");

                    b.HasIndex("Status", "NextRunAt", "DispatchLeaseUntilUtc")
                        .HasDatabaseName("ix_workflows_status_next_run_at_dispatch_lease_until_utc");

                    b.HasIndex("UserId", "NormalizedInstruction", "RecurrenceKind", "DaysOfWeekMask", "LocalTime", "TimeZoneId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflows_user_id_normalized_instruction_recurrence_kind_da")
                        .HasFilter("status = 'Active'");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Entities.FavoriteModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("model_id");

                    b.Property<string>("PreferenceId")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("preference_id");

                    b.HasKey("Id")
                        .HasName("pk_favorite_models");

                    b.HasIndex("PreferenceId")
                        .HasDatabaseName("ix_favorite_models_preference_id");

                    b.HasIndex("PreferenceId", "ModelId")
                        .IsUnique()
                        .HasDatabaseName("ix_favorite_models_preference_id_model_id");

                    b.ToTable("favorite_models", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Entities.Instruction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("PreferenceId")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("preference_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_instructions");

                    b.HasIndex("PreferenceId")
                        .HasDatabaseName("ix_instructions_preference_id");

                    b.HasIndex("PreferenceId", "Priority")
                        .IsUnique()
                        .HasDatabaseName("ix_instructions_preference_id_priority");

                    b.ToTable("instructions", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Entities.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EditedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("edited_at");

                    b.Property<long?>("InputTokenCount")
                        .HasColumnType("bigint")
                        .HasColumnName("input_token_count");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_content");

                    b.Property<string>("MessageRole")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("message_role");

                    b.Property<long?>("OutputTokenCount")
                        .HasColumnType("bigint")
                        .HasColumnName("output_token_count");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('english', message_content)", true);

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<string>("SourcesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("sources_json");

                    b.Property<long?>("TotalTokenCount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_token_count");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("ix_messages_chat_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_messages_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("ChatId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_messages_chat_id_sequence_number");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Entities.WorkflowRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("text")
                        .HasColumnName("failure_message");

                    b.Property<string>("InstructionSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instruction_snapshot");

                    b.Property<string>("ModelIdUsed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("model_id_used");

                    b.Property<string>("ResultMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("result_markdown");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamptz")
                        .HasColumnName("scheduled_for");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("skip_reason");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("status");

                    b.Property<string>("TitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title_snapshot");

                    b.Property<bool>("UseWebSearchUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("use_web_search_used");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_runs");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_workflow_runs_workflow_id");

                    b.HasIndex("WorkflowId", "ScheduledFor")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_runs_workflow_id_scheduled_for");

                    b.ToTable("workflow_runs", (string)null);
                });

            modelBuilder.Entity("Main.Domain.ReadModels.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarKey")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("avatar_key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("display_name");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("email_address");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("EmailAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_address");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Main.Infrastructure.Data.Entities.MemoryRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id");

                    b.Property<int>("AccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("access_count");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<int>("Importance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("importance");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("LastAccessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_accessed_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_memories");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_memories_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_memories_user_id");

                    b.HasIndex("UserId", "IsActive", "CreatedAt")
                        .HasDatabaseName("ix_memories_user_id_is_active_created_at");

                    b.ToTable("memories", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("receive_count");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_inbox_state");

                    b.HasAlternateKey("MessageId", "ConsumerId")
                        .HasName("ak_inbox_state_message_id_consumer_id");

                    b.HasIndex("Delivered")
                        .HasDatabaseName("ix_inbox_state_delivered");

                    b.ToTable("inbox_state", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("destination_address");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueue_time");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fault_address");

                    b.Property<string>("Headers")
                        .HasColumnType("text")
                        .HasColumnName("headers");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_consumer_id");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiator_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("response_address");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_time");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_address");

                    b.HasKey("SequenceNumber")
                        .HasName("pk_outbox_message");

                    b.HasIndex("EnqueueTime")
                        .HasDatabaseName("ix_outbox_message_enqueue_time");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("ix_outbox_message_expiration_time");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_outbox_id_sequence_number");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("OutboxId")
                        .HasName("pk_outbox_state");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_outbox_state_created");

                    b.ToTable("outbox_state", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Aggregates.Chat", b =>
                {
                    b.HasOne("Main.Domain.Aggregates.Folder", null)
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chats_folders_folder_id");
                });

            modelBuilder.Entity("Main.Domain.Aggregates.SharedChat", b =>
                {
                    b.OwnsMany("Main.Domain.ValueObjects.SharedChatMessage", "SharedChatMessages", b1 =>
                        {
                            b1.Property<string>("SharedChatId")
                                .HasColumnType("varchar(30)")
                                .HasColumnName("shared_chat_id");

                            b1.Property<int>("SequenceNumber")
                                .HasColumnType("integer")
                                .HasColumnName("sequence_number");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("created_at");

                            b1.Property<DateTimeOffset>("EditedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("edited_at");

                            b1.Property<string>("MessageContent")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("message_content");

                            b1.Property<string>("MessageRole")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("message_role");

                            b1.HasKey("SharedChatId", "SequenceNumber")
                                .HasName("pk_shared_chat_messages");

                            b1.ToTable("shared_chat_messages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SharedChatId")
                                .HasConstraintName("fk_shared_chat_messages_shared_chats_shared_chat_id");
                        });

                    b.Navigation("SharedChatMessages");
                });

            modelBuilder.Entity("Main.Domain.Entities.FavoriteModel", b =>
                {
                    b.HasOne("Main.Domain.Aggregates.Preference", null)
                        .WithMany("FavoriteModels")
                        .HasForeignKey("PreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorite_models_preferences_preference_id");
                });

            modelBuilder.Entity("Main.Domain.Entities.Instruction", b =>
                {
                    b.HasOne("Main.Domain.Aggregates.Preference", null)
                        .WithMany("Instructions")
                        .HasForeignKey("PreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instructions_preferences_preference_id");
                });

            modelBuilder.Entity("Main.Domain.Entities.Message", b =>
                {
                    b.HasOne("Main.Domain.Aggregates.Chat", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_chats_chat_id");

                    b.OwnsOne("Main.Domain.ValueObjects.Attachment", "Attachment", b1 =>
                        {
                            b1.Property<string>("MessageId")
                                .HasColumnType("varchar(30)")
                                .HasColumnName("id");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("varchar(512)")
                                .HasColumnName("attachment_content_type");

                            b1.Property<string>("FileKey")
                                .IsRequired()
                                .HasColumnType("varchar(512)")
                                .HasColumnName("attachment_file_key");

                            b1.Property<long>("FileSizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("attachment_file_size_in_bytes");

                            b1.HasKey("MessageId");

                            b1.ToTable("messages");

                            b1.WithOwner()
                                .HasForeignKey("MessageId")
                                .HasConstraintName("fk_messages_messages_id");
                        });

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("Main.Domain.Entities.WorkflowRun", b =>
                {
                    b.HasOne("Main.Domain.Aggregates.Workflow", null)
                        .WithMany("WorkflowRuns")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_runs_workflows_workflow_id");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .HasConstraintName("fk_outbox_message_outbox_state_outbox_id");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId")
                        .HasConstraintName("fk_outbox_message_inbox_state_inbox_message_id_inbox_consumer_");
                });

            modelBuilder.Entity("Main.Domain.Aggregates.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Main.Domain.Aggregates.Preference", b =>
                {
                    b.Navigation("FavoriteModels");

                    b.Navigation("Instructions");
                });

            modelBuilder.Entity("Main.Domain.Aggregates.Workflow", b =>
                {
                    b.Navigation("WorkflowRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
