// <auto-generated />
using System;
using System.Collections.Generic;
using Auth.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auth.Infrastructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auth.Domain.Aggregates.EmailChangeRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("OtpTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("otp_token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CurrentEmailAddress", "Auth.Domain.Aggregates.EmailChangeRequest.CurrentEmailAddress#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("varchar")
                                .HasColumnName("current_email_address");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Fingerprint", "Auth.Domain.Aggregates.EmailChangeRequest.Fingerprint#Fingerprint", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ComputedHash")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_computed_hash");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_ip_address");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_language");

                            b1.Property<string>("NormalizedBrowser")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_browser");

                            b1.Property<string>("NormalizedOs")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_os");

                            b1.Property<string>("Timezone")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_timezone");

                            b1.Property<string>("UserAgent")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_user_agent");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NewEmailAddress", "Auth.Domain.Aggregates.EmailChangeRequest.NewEmailAddress#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("varchar")
                                .HasColumnName("new_email_address");
                        });

                    b.HasKey("Id")
                        .HasName("pk_email_change_requests");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_email_change_requests_created_at");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_email_change_requests_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_change_requests_user_id");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_email_change_requests_user_id_expires_at")
                        .HasFilter("completed_at IS NULL AND cancelled_at IS NULL");

                    b.ToTable("email_change_requests", (string)null);
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.LoginRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("MagicLinkTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("magic_link_token_hash");

                    b.Property<string>("OtpTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("otp_token_hash");

                    b.Property<string>("TokenKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("token_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Fingerprint", "Auth.Domain.Aggregates.LoginRequest.Fingerprint#Fingerprint", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ComputedHash")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_computed_hash");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_ip_address");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_language");

                            b1.Property<string>("NormalizedBrowser")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_browser");

                            b1.Property<string>("NormalizedOs")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_os");

                            b1.Property<string>("Timezone")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_timezone");

                            b1.Property<string>("UserAgent")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_user_agent");
                        });

                    b.HasKey("Id")
                        .HasName("pk_login_requests");

                    b.HasIndex("ConsumedAt")
                        .HasDatabaseName("ix_login_requests_consumed_at");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_login_requests_expires_at");

                    b.HasIndex("TokenKey")
                        .IsUnique()
                        .HasDatabaseName("ix_login_requests_token_key");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_login_requests_user_id");

                    b.HasIndex("TokenKey", "ConsumedAt", "ExpiresAt")
                        .HasDatabaseName("ix_login_requests_token_key_consumed_at_expires_at");

                    b.ToTable("login_requests", (string)null);
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.RecoveryKeyChain", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastRotatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_rotated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_recovery_key_chains");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_recovery_key_chains_created_at");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_recovery_key_chains_user_id");

                    b.ToTable("recovery_key_chains", (string)null);
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.RecoveryRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(29)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("MagicLinkTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("magic_link_token_hash");

                    b.Property<DateTimeOffset?>("NewEmailVerifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("new_email_verified_at");

                    b.Property<string>("OtpTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("otp_token_hash");

                    b.Property<string>("TokenKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("token_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Fingerprint", "Auth.Domain.Aggregates.RecoveryRequest.Fingerprint#Fingerprint", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ComputedHash")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_computed_hash");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_ip_address");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_language");

                            b1.Property<string>("NormalizedBrowser")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_browser");

                            b1.Property<string>("NormalizedOs")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_os");

                            b1.Property<string>("Timezone")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_timezone");

                            b1.Property<string>("UserAgent")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_user_agent");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NewEmailAddress", "Auth.Domain.Aggregates.RecoveryRequest.NewEmailAddress#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("varchar")
                                .HasColumnName("new_email_address");
                        });

                    b.HasKey("Id")
                        .HasName("pk_recovery_requests");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_recovery_requests_created_at");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_recovery_requests_expires_at");

                    b.HasIndex("TokenKey")
                        .IsUnique()
                        .HasDatabaseName("ix_recovery_requests_token_key");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_recovery_requests_user_id");

                    b.ToTable("recovery_requests", (string)null);
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_refreshed_at");

                    b.Property<string>("OldRefreshTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("old_refresh_token_hash");

                    b.Property<string>("OldRefreshTokenKey")
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("old_refresh_token_key");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("refresh_token_hash");

                    b.Property<string>("RefreshTokenKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("refresh_token_key");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Fingerprint", "Auth.Domain.Aggregates.Session.Fingerprint#Fingerprint", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ComputedHash")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_computed_hash");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_ip_address");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_language");

                            b1.Property<string>("NormalizedBrowser")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_browser");

                            b1.Property<string>("NormalizedOs")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_os");

                            b1.Property<string>("Timezone")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_timezone");

                            b1.Property<string>("UserAgent")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_user_agent");
                        });

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_sessions_expires_at");

                    b.HasIndex("OldRefreshTokenKey")
                        .HasDatabaseName("ix_sessions_old_refresh_token_key");

                    b.HasIndex("RefreshTokenKey")
                        .IsUnique()
                        .HasDatabaseName("ix_sessions_refresh_token_key");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("ix_sessions_revoked_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.HasIndex("ExpiresAt", "RevokedAt")
                        .HasDatabaseName("ix_sessions_expires_at_revoked_at");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_sessions_user_id_revoked_at");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarKey")
                        .HasColumnType("varchar")
                        .HasColumnName("avatar_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasColumnName("display_name");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar")
                        .HasColumnName("email_address");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_users_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_users_deleted_at")
                        .HasFilter("deleted_at IS NOT NULL");

                    b.HasIndex("EmailAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_address");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("ix_users_is_verified");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Auth.Domain.Entities.RecoveryKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("identifier");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("RecoveryKeyChainId")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("recovery_key_chain_id");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("used_at");

                    b.Property<string>("VerifierHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("verifier_hash");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Fingerprint", "Auth.Domain.Entities.RecoveryKey.Fingerprint#Fingerprint", b1 =>
                        {
                            b1.Property<string>("ComputedHash")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_computed_hash");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_ip_address");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_language");

                            b1.Property<string>("NormalizedBrowser")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_browser");

                            b1.Property<string>("NormalizedOs")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_os");

                            b1.Property<string>("Timezone")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_timezone");

                            b1.Property<string>("UserAgent")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_user_agent");
                        });

                    b.HasKey("Id")
                        .HasName("pk_recovery_keys");

                    b.HasIndex("Identifier")
                        .HasDatabaseName("ix_recovery_keys_identifier");

                    b.HasIndex("IsUsed")
                        .HasDatabaseName("ix_recovery_keys_is_used");

                    b.HasIndex("RecoveryKeyChainId")
                        .HasDatabaseName("ix_recovery_keys_recovery_key_chain_id");

                    b.HasIndex("Identifier", "IsUsed")
                        .HasDatabaseName("ix_recovery_keys_identifier_is_used");

                    b.HasIndex("RecoveryKeyChainId", "IsUsed")
                        .HasDatabaseName("ix_recovery_keys_recovery_key_chain_id_is_used");

                    b.ToTable("recovery_keys", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("receive_count");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_inbox_state");

                    b.HasAlternateKey("MessageId", "ConsumerId")
                        .HasName("ak_inbox_state_message_id_consumer_id");

                    b.HasIndex("Delivered")
                        .HasDatabaseName("ix_inbox_state_delivered");

                    b.ToTable("inbox_state", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("destination_address");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueue_time");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fault_address");

                    b.Property<string>("Headers")
                        .HasColumnType("text")
                        .HasColumnName("headers");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_consumer_id");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiator_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("response_address");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_time");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_address");

                    b.HasKey("SequenceNumber")
                        .HasName("pk_outbox_message");

                    b.HasIndex("EnqueueTime")
                        .HasDatabaseName("ix_outbox_message_enqueue_time");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("ix_outbox_message_expiration_time");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_outbox_id_sequence_number");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("OutboxId")
                        .HasName("pk_outbox_state");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_outbox_state_created");

                    b.ToTable("outbox_state", (string)null);
                });

            modelBuilder.Entity("Auth.Domain.Entities.RecoveryKey", b =>
                {
                    b.HasOne("Auth.Domain.Aggregates.RecoveryKeyChain", null)
                        .WithMany("RecoveryKeys")
                        .HasForeignKey("RecoveryKeyChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recovery_keys_recovery_key_chains_recovery_key_chain_id");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .HasConstraintName("fk_outbox_message_outbox_state_outbox_id");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId")
                        .HasConstraintName("fk_outbox_message_inbox_state_inbox_message_id_inbox_consumer_");
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.RecoveryKeyChain", b =>
                {
                    b.Navigation("RecoveryKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
